[tool.mypy]
show_error_codes = true
warn_unreachable = true
namespace_packages = false
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true

[tool.ruff]
lint.ignore = ["E501"]
lint.extend-select = ["I001"]
exclude = ["__init__.py"]
fix = true
